name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: |
          go build  ./...

      - name: Test
        run: go test -gcflags=-l -v  ./...

      - name: Vet & Lint
        run: |
          go vet ./...
          golint -set_exit_status=1 ./...
